### Site info:
title: Who Tested This?
tagline: Thoughts on testing, development, and life
author: Dan Woodward
email: woody@demondogs.com
description: "Thoughts on testing, development, and life" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Testing, Development, Ruby"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://woodybrood.github.io/" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: woodybrood
github_username:  woodybrood
disqus_shortname:
favicon:     "/images/favicon.ico"
aboutme: Dan Woodward is a tester, gamer, and all around know-it-all. # these are shown on aboutme-sidebar.
aboutme_photo: /images/dan_profile.jpg # your photo.
google_analytics_key:  # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: The Clean Code Blog
        href: http://bloc.cleancoder.com
        title: Uncle Bob's thoughts on development
      - name: Macstories
        href: http://macstories.net
        title: One of the best places for Apple related news
      - name: Brett Terpstra
        href: http://brettterpstra.com
        title: Brett is a fantastic creator of tools for mac users
      - name: One Thing Well
        href: http://onethingwell.org
        title: Each day new tools that do one thing, but do it well


### Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# redcarpet:
#   extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
#highlighter: rouge
kramdown:
    input: GFM
    highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
